### ISSUE TITLE
F1, F2, etc. always act as standard function keys (never as the labeled special features)

### ISSUE THREAD

**Issue by thoelze1** [tekezo/Karabiner-VirtualHIDDevice#1]
In system preferences, there is a checkbox labeled:

> Use F1, F2, etc. keys as standard function keys
> When this option is selected, press the Fn key to use the special features printed on each key.

Regardless of whether this box is checked or not, and regardless of whether Fn is held, the function keys always act as standard function keys.

For example, when I add `kHIDUsage_KeyboardF1` to an `hid_report::input_report` and post it with `post_keyboard_input_report`, then my desktop environment still receives an F1 keypress (as opposed to a brightness_decrement keypress). All other keys work as expected, and can be properly modified with Fn as a modifier.

Is this the expected behavior of the virtual hid device?

**Comment by tekezo** [comment]
Yes.
macOS does not interpret the fx keys as media keys.
You have to post consumer usage page if you want to use these keys as media keys.

**Comment by thoelze1** [comment]
Thanks for responding. Follow up question:

My understanding is that the IOKit sees the Karabiner-VirtualHIDDevice as a physical keyboard. But when a physical keyboard sends the F1 keycode to the OS, then the OS translates it to brightness_decrement by default (but does no translation if the F1 keycode is modified with Fn). The same is not true for the Karabiner-VirtualHIDDevice, as you said. Why is this? What is the difference between the Karabiner-VirtualHIDDevice and a physical keyboard that is responsible for this?

**Comment by tekezo** [comment]
If you have external USB or bluetooth keyboard, you can confirm macOS does not translate the fx keys from the external keyboard.
macOS treats Apple keyboards as special device by their keyboard driver.

((Karabiner-Elements also changes the fx keys like Apple keyboards.)

**Comment by thoelze1** [comment]
I now see that an F1 keypress from a non-Apple external keyboard is always treated as an F1 keypress (earlier, pressing F1 from that keyboard resulted in brightness decrement, but I must have had Karabiner-Elements running and not realized). Thanks for explaining
